language: objective-c

osx_image: xcode8.1
xcode_workspace: TDConnectIosSdk.xcworkspace
xcode_scheme: TDConnectIosSdkTests
xcode_sdk: iphonesimulator

before_install:
  - travis_wait pod repo update

script:
  - xcodebuild -workspace TDConnectIosSdk.xcworkspace -scheme TDConnectIosSdk -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' build
  - xcodebuild -workspace TDConnectIosSdk.xcworkspace -scheme TDConnectIosSdkTests -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' build test
